let colors = ["red", "green", "blue"];
colors.push("yellow");
console.log(colors);    
colors.pop("yellow");
console.log(colors);
let secondcolor=colors[1];
console.log(secondcolor);
let isOrangeIncluded=colors.includes("orange");
console.log(isOrangeIncluded);
for (let i=0;i<colors.length ; i++){
    console.log(colors[i]);
}
let number =[1,2,3,4,5];
let doublenumber=number.map(num =>num*2);
console.log(doublenumber);
let number2 =[1,2,3,4,5];
let positivenumber=number2.every(num =>num>0);
console.log(positivenumber);
let dec=["green" ,"blue" ,"dark"];
let indexofgreen=dec.indexOf("green");
console.log(indexofgreen);
let dec1=["green","blue"];
let descendingorder=dec1.sort((a, b) => a - b);
console.log(descendingorder);
let num=[2,4,5,63,3]
let desc=num.sort((a,b) => a-b);
console.log(desc);
let num3=[2,4,1,4,9];
let reverse=num3.reverse();
console.log(reverse);
const num5 =[4,2,13,4,5];
const slicedarray = num5.slice(1,4);
console.log(slicedarray);
let colorss = ["dark","yellow","violet","green","white"];
let firstthreecolors = colorss.slice(0,3);
console.log(firstthreecolors); 
let firstArray=[1,2,3,4];
let secondArray=[5,6,7,8];
let combinedArray = firstArray.concat(secondArray);
console.log(combinedArray);
let duplicates =[1,2,2,3,3,4,4,5,6];
let uniquearray=[...new Set(duplicates)];
console.log(uniquearray);   
let mixedArray=[1, "hello",true,34.2];
let arrayasString =mixedArray.join("","");
console.log(arrayasString);
let mixedArray2=[1,"hello",true,30.4];
let isSameType=mixedArray2.every((el, _,arr)=>typeof el === typeof arr[0]);
console.log(isSameType);
let number0=[2,4,3,87,3,43];
let maximum=Math.max(...number0);
console.log(maximum);